alias ls='ls -FG'
alias phpgrep='find . -type f -name \*php|xargs grep -ni '
alias jsgrep='find . -type f -name \*js|xargs grep -ni '
alias htmlgrep='find . -type f -name \*html|xargs grep -ni '
alias cssgrep='find . -type f -name \*css|xargs grep -ni '
alias lessgrep='find . -type f -name \*less|xargs grep -ni'
alias scalagrep='find . -type f -name \*scala|xargs grep -ni '

# diff ignore whitespace
alias svnshow='svn diff --diff-cmd diff -x -uw -c '

export PS1="\e[0;34m\u\e[0;33m@\e[0;34m\h\e[m \e[0;36m\w\e[m [\j][\#]\e[0;33m$(__git_ps1) $\e[m "

export HISTCONTROL=erasedups
export HISTSIZE=10000
export HISTTIMEFORMAT="%D %T "
export HISTIGNORE="&:ls:exit:history"
shopt -s histappend

export EDITOR=vim

export SBT_OPTS="$SBT_OPTS -Xms512M -Xmx1536M -Xss512M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M"
export SBT_OPTS="$SBT_OPTS -Dfile.encoding=UTF-8"
export SBT_OPTS="$SBT_OPTS -Djava.library.path=/usr/local/lib" # for jzmq
export JAVA_TOOL_OPTIONS='-Dfile.encoding=UTF8'


alias sqlfind='find resources/sql -type f -iname \*\.js  -mtime -5d -ls -or -iname \*\.sql -mtime -5d -ls |grep -vi \.svn'

export ANDROID_HOME=~/android-sdks/

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

source ~/.profile
source ~/.git-completion.bash

export HOMEBREW_PREFIX="/usr/local"
export HOMEBREW_REPOSITORY="/usr/local"
export HOMEBREW_LIBRARY="/usr/local"
export HOMEBREW_CELLAR="/usr/local/Cellar"

export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh

# for scrapy
# http://stackoverflow.com/questions/30964836/scrapy-throws-importerror-cannot-import-name-xmlrpc-client
export PYTHONPATH=/Library/Python/2.7/site-packages:$PYTHONPATH
